import type { SuggestedQuestion } from "./suggested-questions";

/**
 * Generated by `npm run ai:generate-canned-answers` on 2026-09-04T21:51:33.315Z.
 * Do not edit by hand — re-run the script instead. See AI_SPEC.md §5.
 */
export const CANNED_ANSWERS: Record<SuggestedQuestion, string> = {
  "What is Aditya strongest at?": "Aditya’s strengths lie in the intersection of AI, product, and business. He is comfortable with strategy, research, segmentation, and problem framing, and he applies these skills to build and grow products. In building, he focuses on websites, UI/UX, and product design, while his automation expertise spans APIs, webhooks, and workflows. His intelligence toolkit includes LLMs, AI interfaces, and RAG, enabling him to create intelligent product experiences.",
  "What has he built?": "Aditya has built a range of digital products, including websites and applications, and has worked on UI/UX design and product development. He led the creation of Turbotork, an AI‑driven fleet‑service SaaS that grew to 40+ clients and generated over ₹30 L in revenue within five months, and helped secure a $250 K pre‑seed round. He also developed the goSTOPS GTM strategy, a case study on segmentation and marketing. For more detail, see the Turbotork case study at /work/turbotork-data-integration.",
  "Tell me about the goSTOPS project.": "The goSTOPS project is a GTM strategy case study focused on segmentation, marketing, and strategy. It was completed in 2026 and showcases Aditya’s approach to market positioning and customer targeting. For a detailed overview, see the case study page at /​work/gostops‑gtm.",
  "What technologies does he use?": "Aditya’s portfolio lists the following technologies he works with: Next.js, React, Firebase, Razorpay, GSTN, Twilio, and Exotel. These are highlighted in his Turbotork case study, which details the stack used for that AI‑driven fleet‑service SaaS.",
  "What kind of problems does he enjoy?": "Aditya enjoys problems that can be clearly framed and dissected through strategy and research. He is comfortable tackling issues that involve segmentation, problem framing, and building a product roadmap that aligns with business goals. These challenges allow him to apply his skills in AI, automation, and UI/UX to create tangible solutions.",
  "Why should I work with him?": "Aditya Mahajan builds products at the intersection of AI, product, and business, combining strategic thinking with hands‑on execution.  He has led the GTM strategy for goSTOPS and scaled Turbotork from zero to 40+ clients and ₹30 L+ revenue in five months, while also helping secure a $250 K pre‑seed round.  His skill set spans strategy, research, UI/UX, AI interfaces, and automation, and he has practical experience with Next.js, React, Firebase, and APIs.  For more detail, see his case studies at /work/gostops-gtm and /work/turbotork-data-integration."
};

export const CANNED_ANSWERS_GENERATED_AT: string | null = "2026-09-04T21:51:33.319Z";
