import type { SuggestedQuestion } from "./suggested-questions";

/**
 * Generated by `npm run ai:generate-canned-answers` on 2026-09-04T23:57:00.170Z.
 * Do not edit by hand — re-run the script instead. See AI_SPEC.md §5.
 */
export const CANNED_ANSWERS: Record<SuggestedQuestion, string> = {
  "What is Aditya strongest at?": "Aditya’s strongest focus lies at the intersection of AI, product, and business, where he blends strategy, research, and product design to create market‑ready solutions.  He is comfortable with strategy, research, segmentation, problem framing, SQL, and Power BI, and he builds websites and products with a solid UI/UX foundation.  His automation toolkit includes Make, APIs, webhooks, Python, Databricks, and Snowflake, while his intelligence skills cover LLMs, AI agents, AI interfaces, and RAG.  For more detail, see his portfolio page: https://www.adityalab.com.",
  "What has he built?": "Aditya has built a variety of digital products and services. He founded and shipped the Adda D2C e‑commerce venture, creating a Shopify storefront that handled product research, vendor sourcing, and payment integration. In the realm of strategy, he led the goSTOPS GTM strategy case study and is currently heading the Kensara AI GTM and partnership strategy for an AI startup. For more detail, see the project pages on his site.",
  "Tell me about the goSTOPS project.": "The goSTOPS project is a GTM strategy case study completed in 2026, focused on strategy, marketing, and segmentation. It showcases Aditya’s approach to market positioning and customer segmentation for a transportation‑related initiative. For details, see the case study page: <https://adityalab.com/work/gostops-gtm>.",
  "What technologies does he use?": "I don't have that in Aditya's portfolio.",
  "What kind of problems does he enjoy?": "I don't have that in Aditya's portfolio. The portfolio lists his skills in strategy, research, segmentation, and problem framing, but does not specify the types of problems he enjoys. For more detail, you can view his case studies at /work/gostops-gtm or /work/kensara-ai-gtm.",
  "Why should I work with him?": "Aditya Mahajan’s portfolio demonstrates a blend of AI, product, and business expertise, with hands‑on experience leading GTM strategies for AI startups and building a full Shopify e‑commerce venture. His work on goSTOPS and Kensara AI showcases strategic thinking and partnership development, while Adda highlights end‑to‑end product execution. For more detail, see his case studies at /work/gostops-gtm, /work/kensara-ai-gtm, and /work/adda-d2c."
};

export const CANNED_ANSWERS_GENERATED_AT: string | null = "2026-09-04T23:57:00.171Z";
