import { REFUSAL_STRING } from "./system-prompt";
import type { SuggestedQuestion } from "./suggested-questions";

/**
 * Pre-generated static answers for the six suggested questions (AI_SPEC.md
 * §5/§9) — served with zero API calls. Regenerated by
 * `npm run ai:generate-canned-answers` once a Groq key is configured AND
 * the underlying /data content has been reviewed (CONTENT_TODO.md must be
 * clear of the fields these questions touch) — see scripts/generate-canned-answers.mjs.
 *
 * Until then, every entry is the honest refusal: most of the corpus these
 * questions would draw on is still an unfilled placeholder or an
 * unreviewed AI draft (CLAUDE.md §7), so the refusal string is the
 * factually correct answer today, not a fallback. Never hand-write prose
 * here — that would be inventing content CLAUDE.md §3 forbids.
 */
export const CANNED_ANSWERS: Record<SuggestedQuestion, string> = {
  "What is Aditya strongest at?": REFUSAL_STRING,
  "What has he built?": REFUSAL_STRING,
  "Tell me about the goSTOPS project.": REFUSAL_STRING,
  "What technologies does he use?": REFUSAL_STRING,
  "What kind of problems does he enjoy?": REFUSAL_STRING,
  "Why should I work with him?": REFUSAL_STRING,
};

export const CANNED_ANSWERS_GENERATED_AT: string | null = null;
